version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

registries:
  github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/krickert/rag-models
    username: krickert
    password: ${{secrets.GH_PAT}}
