openapi: 3.0.1
info:
  title: chunker
  version: "0.0"
paths:
  /chunker/chunk-text:
    get:
      operationId: getChunkText
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
      - name: chunkSize
        in: query
        required: true
        schema:
          type: string
      - name: overlapSize
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getChunkText 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      operationId: postChunkText
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TextRequestBody"
        required: true
      responses:
        "200":
          description: postChunkText 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /chunker/chunk-text-split-newline:
    get:
      operationId: getChunkTextSplitNewline
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
      - name: chunkSize
        in: query
        required: true
        schema:
          type: string
      - name: overlapSize
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getChunkTextSplitNewline 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      operationId: postChunkTextSplitNewline
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TextRequestBody"
        required: true
      responses:
        "200":
          description: postChunkTextSplitNewline 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /chunker/squish:
    get:
      operationId: getSquish
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getSquish 200 response
          content:
            text/plain:
              schema:
                type: string
    post:
      operationId: postSquish
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StringRequestRecord"
        required: true
      responses:
        "200":
          description: postSquish 200 response
          content:
            text/plain:
              schema:
                type: string
  /chunker/squish-text:
    get:
      operationId: getSquishText
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getSquishText 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      operationId: postSquishText
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StringRequestRecord"
        required: true
      responses:
        "200":
          description: postSquishText 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /chunker/transform-urls-to-words:
    get:
      operationId: getTransformUrlsToWords
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getTransformUrlsToWords 200 response
          content:
            text/plain:
              schema:
                type: string
    post:
      operationId: postTransformUrlsToWords
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StringRequestRecord"
        required: true
      responses:
        "200":
          description: postTransformUrlsToWords 200 response
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    StringRequestRecord:
      required:
      - text
      type: object
      properties:
        text:
          type: string
    TextRequestBody:
      required:
      - chunkSize
      - overlapSize
      - text
      type: object
      properties:
        text:
          type: string
        chunkSize:
          type: integer
          format: int32
        overlapSize:
          type: integer
          format: int32
